# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_PSF_XYZ_Dialog_BF_new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PSF_XYZ_Dialog_BF_new(object):
    def setupUi(self, PSF_XYZ_Dialog_BF_new):
        PSF_XYZ_Dialog_BF_new.setObjectName("PSF_XYZ_Dialog_BF_new")
        PSF_XYZ_Dialog_BF_new.resize(1240, 522)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PSF_XYZ_Dialog_BF_new.sizePolicy().hasHeightForWidth())
        PSF_XYZ_Dialog_BF_new.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        PSF_XYZ_Dialog_BF_new.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(PSF_XYZ_Dialog_BF_new)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1213, 494))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.check_hotpixel = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_hotpixel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.check_hotpixel.setFont(font)
        self.check_hotpixel.setObjectName("check_hotpixel")
        self.gridLayout.addWidget(self.check_hotpixel, 10, 0, 1, 1)
        self.checkBox_SavePeaks = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_SavePeaks.setObjectName("checkBox_SavePeaks")
        self.gridLayout.addWidget(self.checkBox_SavePeaks, 14, 0, 1, 1)
        self.label_channel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_channel.setFont(font)
        self.label_channel.setObjectName("label_channel")
        self.gridLayout.addWidget(self.label_channel, 3, 0, 1, 1)
        self.label_objNA = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_objNA.setFont(font)
        self.label_objNA.setObjectName("label_objNA")
        self.gridLayout.addWidget(self.label_objNA, 2, 3, 1, 1)
        self.SpinBox_channel = QtWidgets.QSpinBox(self.layoutWidget)
        self.SpinBox_channel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_channel.sizePolicy().hasHeightForWidth())
        self.SpinBox_channel.setSizePolicy(sizePolicy)
        self.SpinBox_channel.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_channel.setMinimum(1)
        self.SpinBox_channel.setMaximum(6)
        self.SpinBox_channel.setObjectName("SpinBox_channel")
        self.gridLayout.addWidget(self.SpinBox_channel, 3, 1, 1, 1)
        self.ExEm_text = QtWidgets.QLabel(self.layoutWidget)
        self.ExEm_text.setAlignment(QtCore.Qt.AlignCenter)
        self.ExEm_text.setObjectName("ExEm_text")
        self.gridLayout.addWidget(self.ExEm_text, 4, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 5, 0, 1, 6)
        self.SpinBox_NA = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_NA.sizePolicy().hasHeightForWidth())
        self.SpinBox_NA.setSizePolicy(sizePolicy)
        self.SpinBox_NA.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_NA.setMinimum(0.0)
        self.SpinBox_NA.setMaximum(1.7)
        self.SpinBox_NA.setSingleStep(0.01)
        self.SpinBox_NA.setProperty("value", 0.0)
        self.SpinBox_NA.setObjectName("SpinBox_NA")
        self.gridLayout.addWidget(self.SpinBox_NA, 2, 4, 1, 1)
        self.text_filename = QtWidgets.QLineEdit(self.layoutWidget)
        self.text_filename.setEnabled(True)
        self.text_filename.setObjectName("text_filename")
        self.gridLayout.addWidget(self.text_filename, 0, 0, 1, 5)
        self.OpenFile = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OpenFile.setFont(font)
        self.OpenFile.setObjectName("OpenFile")
        self.gridLayout.addWidget(self.OpenFile, 0, 5, 1, 1)
        self.label_objname = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_objname.setFont(font)
        self.label_objname.setObjectName("label_objname")
        self.gridLayout.addWidget(self.label_objname, 2, 0, 1, 1)
        self.label_threshold = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_threshold.setFont(font)
        self.label_threshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_threshold.setObjectName("label_threshold")
        self.gridLayout.addWidget(self.label_threshold, 6, 0, 1, 1)
        self.SpinBox_threshold = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_threshold.sizePolicy().hasHeightForWidth())
        self.SpinBox_threshold.setSizePolicy(sizePolicy)
        self.SpinBox_threshold.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_threshold.setToolTip("")
        self.SpinBox_threshold.setMaximum(1.0)
        self.SpinBox_threshold.setSingleStep(0.01)
        self.SpinBox_threshold.setProperty("value", 0.5)
        self.SpinBox_threshold.setObjectName("SpinBox_threshold")
        self.gridLayout.addWidget(self.SpinBox_threshold, 6, 1, 1, 1)
        self.label_pixsize = QtWidgets.QLabel(self.layoutWidget)
        self.label_pixsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pixsize.setObjectName("label_pixsize")
        self.gridLayout.addWidget(self.label_pixsize, 7, 0, 1, 1)
        self.SpinBox_pixsize = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.SpinBox_pixsize.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_pixsize.sizePolicy().hasHeightForWidth())
        self.SpinBox_pixsize.setSizePolicy(sizePolicy)
        self.SpinBox_pixsize.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_pixsize.setToolTip("")
        self.SpinBox_pixsize.setDecimals(1)
        self.SpinBox_pixsize.setMinimum(0.0)
        self.SpinBox_pixsize.setMaximum(1000.0)
        self.SpinBox_pixsize.setSingleStep(1.0)
        self.SpinBox_pixsize.setProperty("value", 0.0)
        self.SpinBox_pixsize.setObjectName("SpinBox_pixsize")
        self.gridLayout.addWidget(self.SpinBox_pixsize, 7, 1, 1, 1)
        self.label_guess_fwhmz = QtWidgets.QLabel(self.layoutWidget)
        self.label_guess_fwhmz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_guess_fwhmz.setObjectName("label_guess_fwhmz")
        self.gridLayout.addWidget(self.label_guess_fwhmz, 8, 0, 1, 1)
        self.SpinBox_guess_fwhmz = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_guess_fwhmz.sizePolicy().hasHeightForWidth())
        self.SpinBox_guess_fwhmz.setSizePolicy(sizePolicy)
        self.SpinBox_guess_fwhmz.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_guess_fwhmz.setToolTip("")
        self.SpinBox_guess_fwhmz.setDecimals(2)
        self.SpinBox_guess_fwhmz.setMinimum(0.1)
        self.SpinBox_guess_fwhmz.setMaximum(5.0)
        self.SpinBox_guess_fwhmz.setSingleStep(0.1)
        self.SpinBox_guess_fwhmz.setProperty("value", 1.5)
        self.SpinBox_guess_fwhmz.setObjectName("SpinBox_guess_fwhmz")
        self.gridLayout.addWidget(self.SpinBox_guess_fwhmz, 8, 1, 1, 1)
        self.SpinBox_zspacing = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.SpinBox_zspacing.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_zspacing.sizePolicy().hasHeightForWidth())
        self.SpinBox_zspacing.setSizePolicy(sizePolicy)
        self.SpinBox_zspacing.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_zspacing.setMinimum(0.0)
        self.SpinBox_zspacing.setMaximum(5.0)
        self.SpinBox_zspacing.setSingleStep(0.0025)
        self.SpinBox_zspacing.setProperty("value", 0.0)
        self.SpinBox_zspacing.setObjectName("SpinBox_zspacing")
        self.gridLayout.addWidget(self.SpinBox_zspacing, 7, 4, 1, 1)
        self.writexls = QtWidgets.QCheckBox(self.layoutWidget)
        self.writexls.setEnabled(True)
        self.writexls.setObjectName("writexls")
        self.gridLayout.addWidget(self.writexls, 13, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 6)
        self.label_ExEm = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ExEm.setFont(font)
        self.label_ExEm.setObjectName("label_ExEm")
        self.gridLayout.addWidget(self.label_ExEm, 4, 0, 1, 1)
        self.objname_text = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objname_text.sizePolicy().hasHeightForWidth())
        self.objname_text.setSizePolicy(sizePolicy)
        self.objname_text.setMinimumSize(QtCore.QSize(200, 0))
        self.objname_text.setAlignment(QtCore.Qt.AlignCenter)
        self.objname_text.setObjectName("objname_text")
        self.gridLayout.addWidget(self.objname_text, 2, 1, 1, 1)
        self.SpinBox_subimage_size = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_subimage_size.sizePolicy().hasHeightForWidth())
        self.SpinBox_subimage_size.setSizePolicy(sizePolicy)
        self.SpinBox_subimage_size.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_subimage_size.setMinimum(5)
        self.SpinBox_subimage_size.setMaximum(30)
        self.SpinBox_subimage_size.setProperty("value", 12)
        self.SpinBox_subimage_size.setObjectName("SpinBox_subimage_size")
        self.gridLayout.addWidget(self.SpinBox_subimage_size, 6, 4, 1, 1)
        self.SpinBox_offset = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_offset.sizePolicy().hasHeightForWidth())
        self.SpinBox_offset.setSizePolicy(sizePolicy)
        self.SpinBox_offset.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_offset.setMinimum(0)
        self.SpinBox_offset.setMaximum(50000)
        self.SpinBox_offset.setProperty("value", 0)
        self.SpinBox_offset.setObjectName("SpinBox_offset")
        self.gridLayout.addWidget(self.SpinBox_offset, 8, 4, 1, 1)
        self.checkBox_SaveOrthoView = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_SaveOrthoView.setObjectName("checkBox_SaveOrthoView")
        self.gridLayout.addWidget(self.checkBox_SaveOrthoView, 13, 2, 1, 1)
        self.checkBox_SavePSFVolume = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_SavePSFVolume.setObjectName("checkBox_SavePSFVolume")
        self.gridLayout.addWidget(self.checkBox_SavePSFVolume, 14, 2, 1, 1)
        self.pushButton_StartCalc = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_StartCalc.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_StartCalc.setFont(font)
        self.pushButton_StartCalc.setObjectName("pushButton_StartCalc")
        self.gridLayout.addWidget(self.pushButton_StartCalc, 14, 4, 1, 2)
        self.label_Immersion = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Immersion.setFont(font)
        self.label_Immersion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Immersion.setObjectName("label_Immersion")
        self.gridLayout.addWidget(self.label_Immersion, 3, 3, 1, 1)
        self.immersion_text = QtWidgets.QLabel(self.layoutWidget)
        self.immersion_text.setAlignment(QtCore.Qt.AlignCenter)
        self.immersion_text.setObjectName("immersion_text")
        self.gridLayout.addWidget(self.immersion_text, 3, 4, 1, 1)
        self.label_RI = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_RI.setFont(font)
        self.label_RI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RI.setObjectName("label_RI")
        self.gridLayout.addWidget(self.label_RI, 4, 3, 1, 1)
        self.ri_text = QtWidgets.QLabel(self.layoutWidget)
        self.ri_text.setAlignment(QtCore.Qt.AlignCenter)
        self.ri_text.setObjectName("ri_text")
        self.gridLayout.addWidget(self.ri_text, 4, 4, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 12, 0, 1, 6)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 9, 0, 1, 6)
        self.SpinBox_hotpix_thresh = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.SpinBox_hotpix_thresh.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_hotpix_thresh.sizePolicy().hasHeightForWidth())
        self.SpinBox_hotpix_thresh.setSizePolicy(sizePolicy)
        self.SpinBox_hotpix_thresh.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_hotpix_thresh.setToolTip("")
        self.SpinBox_hotpix_thresh.setDecimals(0)
        self.SpinBox_hotpix_thresh.setMinimum(255.0)
        self.SpinBox_hotpix_thresh.setMaximum(65535.0)
        self.SpinBox_hotpix_thresh.setSingleStep(1.0)
        self.SpinBox_hotpix_thresh.setProperty("value", 4096.0)
        self.SpinBox_hotpix_thresh.setObjectName("SpinBox_hotpix_thresh")
        self.gridLayout.addWidget(self.SpinBox_hotpix_thresh, 11, 1, 1, 1)
        self.label_hotpixel_threshold = QtWidgets.QLabel(self.layoutWidget)
        self.label_hotpixel_threshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hotpixel_threshold.setObjectName("label_hotpixel_threshold")
        self.gridLayout.addWidget(self.label_hotpixel_threshold, 11, 0, 1, 1)
        self.label_tolerance = QtWidgets.QLabel(self.layoutWidget)
        self.label_tolerance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tolerance.setObjectName("label_tolerance")
        self.gridLayout.addWidget(self.label_tolerance, 11, 2, 1, 1)
        self.SpinBox_tolerance = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.SpinBox_tolerance.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_tolerance.sizePolicy().hasHeightForWidth())
        self.SpinBox_tolerance.setSizePolicy(sizePolicy)
        self.SpinBox_tolerance.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_tolerance.setToolTip("")
        self.SpinBox_tolerance.setDecimals(0)
        self.SpinBox_tolerance.setMinimum(1.0)
        self.SpinBox_tolerance.setMaximum(100.0)
        self.SpinBox_tolerance.setSingleStep(1.0)
        self.SpinBox_tolerance.setProperty("value", 20.0)
        self.SpinBox_tolerance.setObjectName("SpinBox_tolerance")
        self.gridLayout.addWidget(self.SpinBox_tolerance, 11, 3, 1, 1)
        self.label_kernelsize = QtWidgets.QLabel(self.layoutWidget)
        self.label_kernelsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_kernelsize.setObjectName("label_kernelsize")
        self.gridLayout.addWidget(self.label_kernelsize, 11, 4, 1, 1)
        self.SpinBox_kernelsize = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.SpinBox_kernelsize.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_kernelsize.sizePolicy().hasHeightForWidth())
        self.SpinBox_kernelsize.setSizePolicy(sizePolicy)
        self.SpinBox_kernelsize.setMinimumSize(QtCore.QSize(75, 0))
        self.SpinBox_kernelsize.setToolTip("")
        self.SpinBox_kernelsize.setDecimals(0)
        self.SpinBox_kernelsize.setMinimum(2.0)
        self.SpinBox_kernelsize.setMaximum(15.0)
        self.SpinBox_kernelsize.setSingleStep(1.0)
        self.SpinBox_kernelsize.setProperty("value", 2.0)
        self.SpinBox_kernelsize.setObjectName("SpinBox_kernelsize")
        self.gridLayout.addWidget(self.SpinBox_kernelsize, 11, 5, 1, 1)
        self.label_subimage_size = QtWidgets.QLabel(self.layoutWidget)
        self.label_subimage_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_subimage_size.setObjectName("label_subimage_size")
        self.gridLayout.addWidget(self.label_subimage_size, 6, 3, 1, 1)
        self.zspacing = QtWidgets.QLabel(self.layoutWidget)
        self.zspacing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zspacing.setObjectName("zspacing")
        self.gridLayout.addWidget(self.zspacing, 7, 3, 1, 1)
        self.label_offset = QtWidgets.QLabel(self.layoutWidget)
        self.label_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_offset.setObjectName("label_offset")
        self.gridLayout.addWidget(self.label_offset, 8, 3, 1, 1)
        self.label_hotpixel_option = QtWidgets.QLabel(self.layoutWidget)
        self.label_hotpixel_option.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hotpixel_option.setObjectName("label_hotpixel_option")
        self.gridLayout.addWidget(self.label_hotpixel_option, 10, 1, 1, 1)

        self.retranslateUi(PSF_XYZ_Dialog_BF_new)
        QtCore.QMetaObject.connectSlotsByName(PSF_XYZ_Dialog_BF_new)

    def retranslateUi(self, PSF_XYZ_Dialog_BF_new):
        _translate = QtCore.QCoreApplication.translate
        PSF_XYZ_Dialog_BF_new.setWindowTitle(_translate("PSF_XYZ_Dialog_BF_new", "PSF-XYZ Automatic Detection BF V2.0"))
        self.check_hotpixel.setText(_translate("PSF_XYZ_Dialog_BF_new", "Check for HotPixels"))
        self.checkBox_SavePeaks.setText(_translate("PSF_XYZ_Dialog_BF_new", "Save PSF Peaks FWHM"))
        self.label_channel.setText(_translate("PSF_XYZ_Dialog_BF_new", "Select Channel"))
        self.label_objNA.setText(_translate("PSF_XYZ_Dialog_BF_new", "NA"))
        self.ExEm_text.setText(_translate("PSF_XYZ_Dialog_BF_new", "n.a."))
        self.text_filename.setText(_translate("PSF_XYZ_Dialog_BF_new", "imagefile"))
        self.OpenFile.setText(_translate("PSF_XYZ_Dialog_BF_new", "Browse..."))
        self.label_objname.setText(_translate("PSF_XYZ_Dialog_BF_new", "Objective"))
        self.label_threshold.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Threshold used to identify the peaks."))
        self.label_threshold.setText(_translate("PSF_XYZ_Dialog_BF_new", "Threshold [0-1]"))
        self.label_pixsize.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Pixel Size in image plane."))
        self.label_pixsize.setText(_translate("PSF_XYZ_Dialog_BF_new", "Pixel Size [nm]"))
        self.label_guess_fwhmz.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Guess for FWHM-Z used tfor the Gauss Fit."))
        self.label_guess_fwhmz.setText(_translate("PSF_XYZ_Dialog_BF_new", "Guess FWHM-Z [micron]"))
        self.writexls.setText(_translate("PSF_XYZ_Dialog_BF_new", "Write Data to Excel File"))
        self.label_ExEm.setText(_translate("PSF_XYZ_Dialog_BF_new", "EX/EM Wavelength [nm]"))
        self.objname_text.setText(_translate("PSF_XYZ_Dialog_BF_new", "n.a."))
        self.checkBox_SaveOrthoView.setText(_translate("PSF_XYZ_Dialog_BF_new", "Save PSF OrthoView"))
        self.checkBox_SavePSFVolume.setText(_translate("PSF_XYZ_Dialog_BF_new", "Save PSF Volume"))
        self.pushButton_StartCalc.setText(_translate("PSF_XYZ_Dialog_BF_new", "Start Detection"))
        self.label_Immersion.setText(_translate("PSF_XYZ_Dialog_BF_new", "Immersion"))
        self.immersion_text.setText(_translate("PSF_XYZ_Dialog_BF_new", "n.a."))
        self.label_RI.setText(_translate("PSF_XYZ_Dialog_BF_new", "Ref. Index"))
        self.ri_text.setText(_translate("PSF_XYZ_Dialog_BF_new", "n.a."))
        self.label_hotpixel_threshold.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Size of subimage which is cut out to apply the 2D Gauss Fit."))
        self.label_hotpixel_threshold.setText(_translate("PSF_XYZ_Dialog_BF_new", "HotPixel Threshold"))
        self.label_tolerance.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Size of subimage which is cut out to apply the 2D Gauss Fit."))
        self.label_tolerance.setText(_translate("PSF_XYZ_Dialog_BF_new", "Tolerance Cutoff"))
        self.label_kernelsize.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Size of subimage which is cut out to apply the 2D Gauss Fit."))
        self.label_kernelsize.setText(_translate("PSF_XYZ_Dialog_BF_new", "Median Kernel Size"))
        self.label_subimage_size.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Size of subimage which is cut out to apply the 2D Gauss Fit."))
        self.label_subimage_size.setText(_translate("PSF_XYZ_Dialog_BF_new", "Subimage Size [pixel]"))
        self.zspacing.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Distance between 2 focal planes."))
        self.zspacing.setText(_translate("PSF_XYZ_Dialog_BF_new", "Z-Spacing [micron]"))
        self.label_offset.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Size of subimage which is cut out to apply the 2D Gauss Fit."))
        self.label_offset.setText(_translate("PSF_XYZ_Dialog_BF_new", "Subtract Offset CCD [cts]"))
        self.label_hotpixel_option.setToolTip(_translate("PSF_XYZ_Dialog_BF_new", "Size of subimage which is cut out to apply the 2D Gauss Fit."))
        self.label_hotpixel_option.setText(_translate("PSF_XYZ_Dialog_BF_new", "(Optional)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PSF_XYZ_Dialog_BF_new = QtWidgets.QDialog()
    ui = Ui_PSF_XYZ_Dialog_BF_new()
    ui.setupUi(PSF_XYZ_Dialog_BF_new)
    PSF_XYZ_Dialog_BF_new.show()
    sys.exit(app.exec_())

